### ISSUE TITLE
vulnerability in deps

### ISSUE THREAD

**Issue by nduchak** [libp2p/js-libp2p-secio#127]
│ High                         │ Prototype Pollution in node-forge                       
│ Package                  │ node-forge                                                   
│ Patched in               │ >= 0.10.0                                                    
│ Path                         │ @rsksmart/rif-communications-pubsub > libp2p-secio > libp2p-crypto > node-forge 
│ More info                 │ https://npmjs.com/advisories/1561

**Comment by vasco-santos** [comment]
@nduchak thanks for reaching out, but this module is deprecated and not maintained anymore.

We need to archive the repo though

cc @Stebalien as I have no permissions for it
