### ISSUE TITLE
secio Flow Documentation

### ISSUE THREAD

**Issue by daviddias** [libp2p/js-libp2p-secio#15]
@dignifiedquire please document how secio works. A flowgram would be 👌🏽

**Comment by dignifiedquire** [comment]
@diasdavid what was that tool you mentioned for creating ascii diagrams?

**Comment by diasdavid** [comment]
http://monodraw.helftone.com/ is the best :D

**Comment by lgierth** [comment]
http://asciiflow.com/ is also pretty good

**Comment by dignifiedquire** [comment]
I guess I don't have any excuses no

**Comment by jbenet** [comment]
wow, http://monodraw.helftone.com/ has a very nice site

**Comment by diasdavid** [comment]
@jbenet and the tool is even better! :D

**Comment by daviddias** [comment]
Existing docs:

- https://github.com/libp2p/js-libp2p/tree/master/examples/encrypted-communications
- https://github.com/auditdrivencrypto/secure-channel/blob/master/prior-art.md#ipfss-secure-channel

**Comment by robinmonjo** [comment]
Hello all, I'm trying to write a secio implementation in another language. How can I test my work ? My strategy for now is to try to perform a successful handshake with one of the node in the IPFS bootstrap  nodes list but this is really difficult to debug 🤯. Any pointers would be great.

**Comment by mkg20001** [comment]
I've started something here: https://hackmd.io/C3PxZ5R6RR-v7dScRuF03w?both

(hackMD renders the diagram pretty tiny)

There's some stuff missing, feel free to add it

It can be rendered using https://bramp.github.io/js-sequence-diagrams/
