### ISSUE TITLE
Is this suitable for the browser?

### ISSUE THREAD

**Issue by JustinDrake** [libp2p/js-libp2p-secio#34]
I am interested in encrypting and decrypting IPFS communications client-side and wondered if `js-libp2p-secio` is suitable for the browser. Some of my concerns are:

* When doing `npm install`, I notice that some dependencies have C/C++ that needs compiling. Presumably those are Node.JS-only dependencies
* The code is written with ES6 which will need compiling down to ES5 for wide browser support.

On the other hand, I see there is a test file called [`browser.js`](https://github.com/libp2p/js-libp2p-secio/blob/master/test/browser.js) described as `secio browser <-> nodejs` so this is promising!

**Comment by dignifiedquire** [comment]
The code should run out of the box on latest Firefox and Chrome. Even without transpiling. The major blocker for other browsers is webcrypto, which is being tracked here: https://github.com/libp2p/js-libp2p-crypto/issues/18

**Comment by JustinDrake** [comment]
Thanks for pointing out the webcrypto dependency. When you mean "out of the box" how does that work? Should I be using http://browserify.org?

**Comment by dignifiedquire** [comment]
> When you write "out of the box" how does that work? Should I be using http://browserify.org?

Yes you can either use webpack or browserify. You can find examples for js-ipfs on how to do this [here](https://github.com/ipfs/js-ipfs/tree/master/examples), which has the same setup as the js-libp2p modules.
