### ISSUE TITLE
Uncaught error when using browserify

### ISSUE THREAD

**Issue by JustinDrake** [libp2p/js-libp2p-secio#35]
Below is my code. I use Browserify and run the code in Chrome. The code runs `crypto.generateKeyPair` without issues, but chokes on `peerId.createFromPrivKey` with an Uncaught Exception. See screenshot.

```js
const crypto = require('libp2p-crypto')
const peerId = require('peer-id')

// Example: create an identity
crypto.generateKeyPair('RSA', 2048, (err, key) => {
	if(err) {
		console.error(err);
		return err;
	}

	// So far so good!
	console.log(key);

	// Throws an Uncaught Error!
	peerId.createFromPrivKey(key.bytes, (err, id) => {
		if(err) {
			console.error(err);
			return err;
		}

		console.log(id.toB58String());
	});
});
```

<img width="474" alt="screen shot 2016-11-23 at 12 09 30" src="https://cloud.githubusercontent.com/assets/731743/20561335/06aa31fe-b176-11e6-9760-80af8b354515.png">

**Comment by dignifiedquire** [comment]
Thanks for the report, but this is an issue with libp2p-crypto not secio, could you move the issue there please?

**Comment by JustinDrake** [comment]
Done. https://github.com/libp2p/js-libp2p-crypto/issues/41
