### ISSUE TITLE
Add go-interop tests

### ISSUE THREAD

**Issue by dignifiedquire** [libp2p/js-libp2p-secio#4]

**Comment by diasdavid** [comment]
Currently, it is not interoperable because it is using varint prefix instead of 4 byte prefix like in go (which uses msgio) https://github.com/jbenet/go-msgio/issues/13

**Comment by diasdavid** [comment]
What do you need to automate these tests?

**Comment by dignifiedquire** [comment]
Yep a pipe, so I can send back and forth stuff, ideally with some debug flag so it prints out all the things for debugging sessions.

**Comment by diasdavid** [comment]
@whyrusleeping can you make that happen?

**Comment by JustinDrake** [comment]
Just FYI, at [Duo Search](www.duosear.ch) we want a browser-based IPFS bridge for OpenBazaar (built on `go-ipfs`). We want to use `js-secio` client-side and interoperability with `go-ipfs` is necessary for us.

**Comment by diasdavid** [comment]
@JustinDrake js-libp2p-secio interops with go-libp2p-secio (used in js-ipfs and go-ipfs respectively)

What about https://github.com/ipfs/js-ipfs directly?

**Comment by JustinDrake** [comment]
Thanks for clarifying the interoperability with `go-libp2p-secio` @diasdavid. Tests showing that would be awesome.

> What about https://github.com/ipfs/js-ipfs directly?

We want to build an OpenBazaar gateway in the browser for buyers. The objective is that any buyer can do business with vendors privately, without possibility for Duo Search to snoop.

OpenBazaar has quite a bit of complexity with a lot of that complexity in IPFS. Maybe we can put the whole thing in a browser. The good news is that we have support from the Duo Search servers, and a client/server hybrid approach (similar to Blockchain.info's hybrid approach for their Bitcoin wallet) could help us a lot. In particular, I think we should avoid using `js-libp2p` client-side and instead use `go-libp2p` server-side, where the Duo Search servers proxy encrypted messages between buyers and sellers.

My reasons for avoiding `js-libp2p` on the client are listed below. Those may be totally false preconceptions, so please correct me where wrong.

1. Browsers have terrible support for native p2p transports.
2. The worse case scenario (old browsers and/or a complex network topology involving NATs) cannot be handled without support from IPFS gateways.
3. Even in the best case scenario (latest Chrome and a simple network topology), DHT routing can be flaky and slow. The Duo Search servers can provide a much more robust networking foundation.
4. `js-libp2p` is highly experimental compared to `go-libp2p`

**Comment by diasdavid** [comment]
Done through https://github.com/libp2p/interop and https://github.com/ipfs/interop
