### ISSUE TITLE
Stream handshake closed prematurely

### ISSUE THREAD

**Issue by diasdavid** [libp2p/js-libp2p-secio#41]
Error: Stream ended prematurely
    at series (/Users/koruza/code/js-ipfs/node_modules/libp2p-secio/src/handshake/index.js:21:15)

**Comment by dignifiedquire** [comment]
This is not an error on secio, it means the connection was dropped before the handshake could complete.

**Comment by jacobheun** [comment]
This should be closable, as it should be resolved by https://github.com/libp2p/js-libp2p-secio/pull/101, which ensures errors are properly being passed up the callback chain to the dial.
