### ISSUE TITLE
Errors might contain invalid chars

### ISSUE THREAD

**Issue by daviddias** [libp2p/js-libp2p-secio#62]
Got this while running libp2p mapper for a while 
![image](https://cloud.githubusercontent.com/assets/1211152/22856395/6c63a490-f045-11e6-83e5-2a6294588a25.png)

libp2p mapper https://ipfs.io/ipfs/QmWtSgpCBJJNwy3MDNinyG4JV35UP37ruqpUEir9AU2PSf/

**Comment by dignifiedquire** [comment]
This is not about invalid chars. I have seen this error, and I technically know how/why it happens but I haven't found a good way to fix it. This is originating in the key generation inside libp2p-crypto, and related to the method used from webcrypto and the conversion to jwk format.

**Comment by michaelfakhri** [comment]
I have run into this error too and in my case, it occurs in the browser exclusively but I haven't investigated it any further.
