### ISSUE TITLE
Heavy browser performance impact

### ISSUE THREAD

**Issue by Beanow** [libp2p/js-libp2p-secio#92]
Performing a test by `ipfs.files.get` on a larger file, such as a 4MB audio file. Secio processes roughtly 7,5MB of data with AES CTR-mode decrypt here https://github.com/libp2p/js-libp2p-secio/blob/master/src/etm.js#L59.

This process took 249 seconds on a fresh repo (downloading from another tab), 243 seconds of which was spent in Firefox's garbage collection (v55, 64bit Linux) cleaning up the buffers created for decryption. All the while blocking the main thread.

Whereas Chromium consistently farts out.
![image](https://user-images.githubusercontent.com/497556/30007130-27216d22-9108-11e7-970d-7efd1a0aab19.png)

This is a profile where the file was offered by https://orbit.chat/ and downloaded by a different tab.
It doesn't cover the entire 249 seconds, as samples were already being discarded before then.
[profile-secio.json.zip](https://github.com/libp2p/js-libp2p-secio/files/1273303/profile-secio.json.zip)

**Comment by diasdavid** [comment]
Thank you for the throughout report, @Beanow 5🌟

There is a fix incoming specifically for this -- https://github.com/crypto-browserify/browserify-aes/pull/48 -- waiting for a release!

**Comment by ya7ya** [comment]
Hey @Beanow , Thanks for reporting, this is an issue with `browserify-aes` https://github.com/crypto-browserify/browserify-aes/pull/48 , and it got fixed but we're still waiting for release, since this is the main culprit of the issue.

**Comment by ya7ya** [comment]
@Beanow Till it gets released, I [made a fork that uses the unreleased version](https://github.com/ya7ya/js-libp2p-secio) of `browserify-aes` but this is not suitable for anything beyond testing. so please don't use it in production.

**Comment by Beanow** [comment]
:+1: sweet, using the fixed version cuts the same process down to 32 seconds. It went down from >90K GC calls to 3400.

**Comment by Beanow** [comment]
Thanks @ya7ya, what I did though was put a dependency to `"browserify-aes": "github:crypto-browserify/browserify-aes#master"` in my project root and webpack is happy to use it.

**Comment by ya7ya** [comment]
Great, all credit goes to @dignifiedquire :D

**Comment by haadcode** [comment]
Woah! If this fixes what I think it'll fix, this will be a major improvement to the performance. Those ^ numbers sound amazing :) Great work everyone involved, thank you!

**Comment by ya7ya** [comment]
@diasdavid since `libp2p-crypto` is now released and uses https://github.com/crypto-browserify/browserify-aes/pull/48 , Can We get `libp2p-secio` release to use the new `libp2p-crypto` version?

**Comment by diasdavid** [comment]
Not yet, there was an issue with the update to browserify-aes. it got mixed with the no unsafe-eval endeavour) https://github.com/ipfs/js-ipfs/issues/991 which resulted in this big problem https://github.com/ipld/js-ipld-dag-pb/issues/41). I had to unpublish it.



Let me revert the switch to protobufjs done here https://github.com/libp2p/js-libp2p-crypto/commits/master and release it.

**Comment by diasdavid** [comment]
@ya7ya libp2p-crypto@0.10.2 was published with the new browserify-aes. A fresh npm install (don't forget to delete package-lock.json) should get you a less memory hungry IPFS :)

**Comment by Beanow** [comment]
Tested a fresh npm install. This resolved to browserify-aes 1.0.8 and fixes the issue.
Thanks all! It's not every day you get :100:**x** performance boosts days after reporting.
